<?php

namespace Container9sRHlxt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RCWKsCMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RCWKsCM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RCWKsCM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rujukanRepository' => ['privates', 'App\\Repository\\RujukanRepository', 'getRujukanRepositoryService', true],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'rujukanRepository' => 'App\\Repository\\RujukanRepository',
            'taskRepository' => 'App\\Repository\\TaskRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
