<?php

namespace Container9sRHlxt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WoxUadNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.woxUadN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.woxUadN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rujukan' => ['privates', '.errored..service_locator.woxUadN.App\\Entity\\Rujukan', NULL, 'Cannot autowire service ".service_locator.woxUadN": it needs an instance of "App\\Entity\\Rujukan" but this type has been excluded in "config/services.yaml".'],
        ], [
            'rujukan' => 'App\\Entity\\Rujukan',
        ]);
    }
}
