<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rujukan extends \App\Entity\Rujukan implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'bahagians' => [parent::class, 'bahagians', null],
        "\0".parent::class."\0".'flag' => [parent::class, 'flag', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nama' => [parent::class, 'nama', null],
        "\0".parent::class."\0".'tasks' => [parent::class, 'tasks', null],
        "\0".parent::class."\0".'users' => [parent::class, 'users', null],
        'bahagians' => [parent::class, 'bahagians', null],
        'flag' => [parent::class, 'flag', null],
        'id' => [parent::class, 'id', null],
        'nama' => [parent::class, 'nama', null],
        'tasks' => [parent::class, 'tasks', null],
        'users' => [parent::class, 'users', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
