<?php

namespace ContainerExWZTZB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MMmnblService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._mMmnbl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._mMmnbl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rujukanRepository' => ['privates', 'App\\Repository\\RujukanRepository', 'getRujukanRepositoryService', true],
        ], [
            'rujukanRepository' => 'App\\Repository\\RujukanRepository',
        ]);
    }
}
