<?php

namespace ContainerExWZTZB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TWdPnbfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tWdPnbf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tWdPnbf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'user' => ['privates', '.errored..service_locator.tWdPnbf.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.tWdPnbf": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'fileUploader' => 'App\\Service\\FileUploader',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
