<?php

namespace ContainerExWZTZB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRujukan2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.woxUadN.App\Entity\Rujukan' shared service.
     *
     * @return \App\Entity\Rujukan
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.woxUadN": it needs an instance of "App\\Entity\\Rujukan" but this type has been excluded in "config/services.yaml".');
    }
}
